spring:
  application:
    name: Molecule-Discovery
  cloud:
    stream:
      bindings:
        compounds_response:
          destination: queue.compounds.response
        compounds_request:
          destination: queue.compounds.request
        processing_progress:
          destination: queue.processing.out
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        dialect: org.hibernate.dialect.MySQL5Dialect
    open-in-view: false



# Mute unnecessary logs (never ever do that on real app)
logging:
  level:
    root: error
    pl:
      filipowm: debug
    reactor: info
